### ISSUE TITLE
M1 Mac使用Alley_0.1.0_aarch64.dmg无法正常安装。使用64的版本可以

### ISSUE THREAD

**Issue by cat-sir** [alley-rs/alley-transfer#110]
<img width="260" alt="image" src="https://github.com/alley-rs/alley-transfer/assets/71893945/6b69937d-6bd7-4071-bdae-281161e62f25">
大佬，这是啥情况，已经开启了任何来源安装的权限

**Comment by thep0y** [comment]
你是不是直接在 dmg 里打开了？把它拖到右边的 Applications 里，在程序坞里打开。

**Comment by cat-sir** [comment]
> 你不是直接在dmg里打开吗？把它拖到右边的Applications里，在程序坞里打开，再根据README中的“常见问题”操作应该可以解决已损坏的问题。

不是直接在dmg里打开，我都试过，拖到右边Applications安装后再启动台也无法运行，报同样的错误。

**Comment by thep0y** [comment]
> > 你不是直接在dmg里打开吗？把它拖到右边的Applications里，在程序坞里打开，再根据README中的“常见问题”操作应该可以解决已损坏的问题。
> 
> 不是直接在dmg里打开，我都试过，拖到右边Applications安装后再启动台也无法运行，报同样的错误。

你执行命令了吗？

**Comment by cat-sir** [comment]
> > > 你不是直接在dmg里打开吗？把它拖到右边的Applications里，在程序坞里打开，再根据README中的“常见问题”操作应该可以解决已损坏的问题。
> > 
> > 
> > 不是直接在dmg里打开，我都试过，拖到右边Applications安装后再启动台也无法运行，报同样的错误。
> 
> 你执行命令了吗？

执行过。
<img width="499" alt="image" src="https://github.com/alley-rs/alley-transfer/assets/71893945/343c5181-7a80-45c6-906c-1b939e79e1c4">

**Comment by thep0y** [comment]
> > > > 你不是直接在dmg里打开吗？把它拖到右边的Applications里，在程序坞里打开，再根据README中的“常见问题”操作应该可以解决已损坏的问题。
> > > 
> > > 
> > > 不是直接在dmg里打开，我都试过，拖到右边Applications安装后再启动台也无法运行，报同样的错误。
> > 
> > 
> > 你执行命令了吗？
> 
> 执行过。 <img alt="image" width="499" src="https://private-user-images.githubusercontent.com/71893945/305783759-343c5181-7a80-45c6-906c-1b939e79e1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTQ5OTksIm5iZiI6MTcwODMxNDY5OSwicGF0aCI6Ii83MTg5Mzk0NS8zMDU3ODM3NTktMzQzYzUxODEtN2E4MC00NWM2LTkwNmMtMWI5MzllNzllMWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzNTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkY2M0MGY5ZGM5Y2Y2MmMxYTg4ZDkxNzY4MDExNjY0OWU3NGEwOWQ5ZjU5YTRiZTQ5NDY0MTkyZmI0YThkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCHUQXZ__wD3p6XCe9Nr0-RQmZUp1u7nnzfC8jPNc2s">


README 中命令与允许任何来源无关，允许任何来源指的是在非官方渠道下载但经过开发者签名的程序，而小路速传没有经过开发者签名，允许任何来源后对小路速传这种未签名的程序无影响，需要使用 README 中的命令单独信任小路速传。

**Comment by cat-sir** [comment]
> > 执行过
> 
> README 中命令与允许任何来源无关，允许任何来源指的是在非官方渠道下载但经过开发者签名的程序，而小路速传没有经过开发者签名，允许任何来源后对小路速传这种未签名的程序无影响，需要使用 README 中的命令单独信任小路速传。
> 
> 任何来源 = **被认可的开发者**在App Store之外的途径下载的程序。 小路速传 = **未被认可的开发者**开发的程序。
> 
>  output.webm

谢谢！按照你的方式成功了！后续的升级还需要按此操作吗！
非常感谢

**Comment by thep0y** [comment]
> > > 执行过
> > 
> > 
> > README 中命令与允许任何来源无关，允许任何来源指的是在非官方渠道下载但经过开发者签名的程序，而小路速传没有经过开发者签名，允许任何来源后对小路速传这种未签名的程序无影响，需要使用 README 中的命令单独信任小路速传。
> > 任何来源 = **被认可的开发者**在App Store之外的途径下载的程序。 小路速传 = **未被认可的开发者**开发的程序。
> > output.webm
> 
> 谢谢！按照你的方式成功了！后续的升级还需要按此操作吗！ 非常感谢

以后如果手动更新仍需如此操作，如果在应用热更新则不需要。

目前已经实现了应用内热更新，但如果更新渠道不可访问或服务器出问题可能还需手动更新。

**Comment by cat-sir** [comment]
> > > > 执行过
> > > 
> > > 
> > > README 中命令与允许任何来源无关，允许任何来源指的是在非官方渠道下载但经过开发者签名的程序，而小路速传没有经过开发者签名，允许任何来源后对小路速传这种未签名的程序无影响，需要使用 README 中的命令单独信任小路速传。
> > > 任何来源 = **被认可的开发者**在App Store之外的途径下载的程序。 小路速传 = **未被认可的开发者**开发的程序。
> > > output.webm
> > 
> > 
> > 谢谢！按照你的方式成功了！后续的升级还需要按此操作吗！ 非常感谢
> 
> 以后如果手动更新仍需如此操作，如果在应用热更新则不需要。
> 
> 目前已经实现了应用内热更新，但如果更新渠道不可访问或服务器出问题可能还需手动更新。

好的谢谢！那我关闭这个问题。
