### ISSUE TITLE
统计 Debian 10 和 Ubuntu 20.04 用户需求

### ISSUE THREAD

**Issue by thep0y** [alley-rs/alley-transfer#167]
打包环境是 ubuntu 22.04，使用的 glibc 版本比 Debian10 和 Ubuntu 20.04 新一些，会导致程序无法运行。

如果你用的是 Debian10 或 Ubuntu 20..04，在本问题下留言，我会视情况决定是否再编译一个旧版 glibc 的 Linux 程序。

**Comment by 107295472** [comment]
这个怎么不像飞哥传书那样呢 ，发现已登录的端

**Comment by thep0y** [comment]
> 这个怎么不像飞哥传书那样呢 ，发现已登录的端

手机端如果能够适配会考虑添加自动搜索客户端的功能，不然这个功能没有什么意义。

**Comment by thep0y** [comment]
在新版计划中发自我的荣耀手机-------- 原始邮件 --------发件人： lifeforfun ***@***.***>日期： 2024年5月9日周四 16:59收件人： alley-rs/alley-transfer ***@***.***>抄送： thep0y ***@***.***>, Author ***@***.***>主    题： Re: [alley-rs/alley-transfer] 统计 Debian 10 和 Ubuntu 20.04 用户需求 (Issue #167)
建议再加入文本传输，这样在公司内就完全可以抛弃微信的文件传输助手了

**Comment by guobihai** [comment]
how to build window app

**Comment by thep0y** [comment]
> how to build window app

已打包的 windows 的 msi 和 exe 都只是对真正的可执行exe压缩了一下。

如果你只想要可执行exe，需要自己克隆代码进行编译，exe在编译后的`src-tauri/target/release`目录中。

**Comment by guobihai** [comment]
感谢&nbsp;


郭碧海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 晚上6:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alley-rs/alley-transfer] 统计 Debian 10 和 Ubuntu 20.04 用户需求 (Issue #167)














  
how to build window app
  
已打包的 windows 的 msi 和 exe 都只是对真正的可执行exe压缩了一下。
 
如果你只想要可执行exe，需要自己克隆代码进行编译，exe在编译后的src-tauri/target/release目录中。
